### ISSUE TITLE
能否提交到f-droid

### ISSUE THREAD

**Issue by ivysrono** [pppscn/SmsForwarder#196]
f-droid会自动从开源项目源码进行编译并发布，当然需要符合其政策，没有任何不开源的第三方代码。
退一步，还可以由IzzyOnDroid进行收录。
@IzzySoft

**Comment by pppscn** [comment]
提交到f-droid对使用者/开发者而言有什么好处？

**Comment by IzzySoft** [comment]
There's no account needed at F-Droid, so no sign-up. Everyone can use it without being tracked, no walled garden. No Tracking, F-Droid cares for privacy. And only FOSS there, no proprietary components allowed. So currently, the show stopper for SmsForwarder is:

```
Offending libs:
---------------
* Umeng (/com/umeng/analytics): NonFreeDep,Tracking

1 offenders.
```

because of being a `NonFreeDep` (proprietary). If an app has (FOSS) components tracking a user without consent, they'd get the `Tracking` flag visibly set (so users are aware of that before installing, or even can filter it from the list of apps available to not even see it in the first place) – but proprietary components are not allowed, as pointed out above. So we'd need a FOSS build flavor here that comes without Umeng Analytics. If you really need analytics inside the app, you can find [some FOSS alternatives listed here](https://gitlab.com/-/snippets/1896503#acceptable-analytics).

You can find some more details about F-Droid in my article [F-Droid: The privacy-friendly alternative to Google Play Store](https://android.izzysoft.de/articles/named/fdroid-intro-1) – sorry, no Chinese variant available, I only speak German and English fluently enough.

**Comment by pppscn** [comment]
如果只是为了所谓的“信任”那就大可不必了，反正是100%开源的，不信任就自己编译或者直接卸载了

**Comment by pppscn** [comment]
暂不考虑提交到f-droid

**Comment by E021ntox** [comment]
@pppscn 作者能否加个umeng的开关？或者建议直接移除umeng吧，你不收集隐私它自己也会收集。退一步讲用firebase那些都比umeng好得多。。
